# NUMPY -NUMERICAL PYTHON                                                                                  

NOTES BY NIKHIL SHARMA 

In [2]:
import numpy as np

In [3]:
#i-dimensional array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
#numpy contain the same elements 
l=[1,2,3,4,5,"6","abc"]
m=np.array(l)
print(m)

['1' '2' '3' '4' '5' '6' 'abc']


In [7]:
#2d dimensional array 
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("ARRAY IS ",a)
print("THE TYPE OF ARRAYS IS:",type(a))

ARRAY IS  [[1 2 3]
 [4 5 6]]
THE TYPE OF ARRAYS IS: <class 'numpy.ndarray'>


In [8]:
a=[1,2,3]
b=np.array(a*3)
print(b)

[1 2 3 1 2 3 1 2 3]


some functions
1.np.ones()
2.np.zeros()
3.np.full()
4.np.empty()

In [11]:
b=np.ones(3,dtype=int)
print(b)

[1 1 1]


In [16]:
b=np.zeros(3)
print(b)

[0. 0. 0.]


In [19]:
b=np.full(3)   #getting error 
print(b)

TypeError: full() missing 1 required positional argument: 'fill_value'

In [20]:
b=np.ones((3,5),dtype=int)    #3 for rows and 5 for columns 
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
b=np.ones((3,2),dtype=int)
print(b)

[[1 1]
 [1 1]
 [1 1]]


# Finding the dimensions of the Array


The ndim function can be used to find the dimensions of the array.

In [22]:
import numpy as np  
arr = np.array([[[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]]])  
print(arr.ndim)  

3


In [23]:
import numpy as np
a=np.array([1, 3, 5, 7],complex)  
print(a)

[1.+0.j 3.+0.j 5.+0.j 7.+0.j]


Finding the size of each array element
The itemsize function is used to get the size of each array item. It returns the number of bytes taken by each array element.

In [18]:
import numpy as np
a=np.array([[12,3],[4,5,6]])
print(a.itemsize)

8


Finding the shape and size of the array
To get the shape and size of the array, the size and shape function associated with the numpy array is used.

In [24]:
import numpy as np
a=np.array([[1,2,3,4,5,6]])
print(a.size)
print(a.shape)

6
(1, 6)


In [24]:
#numpy.arange([start],stop,[step],dtype=None)

b=np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
b=np.arange(2,10)
print(b)

[2 3 4 5 6 7 8 9]


In [26]:
b=np.arange(2,10,2)
print(b)

[2 4 6 8]


In [31]:
b=np.identity(3,dtype=int)   #IN IDENTITY WE CAN PASSED ONLY ONE ARGUMENT 
print(b)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
b=np.eye(3,2)    #EYE CAN PASSED ONE OR MORE THAN TWO ARGUMENTS 
print(b) 


[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [35]:
b=np.random.rand(3)  #it generates random values 
print(b)

[0.29910944 0.70457547 0.7163732 ]


In [36]:
b=np.random.rand(2,3)  #it generates random values 
print(b)

[[0.05116282 0.9773194  0.90861989]
 [0.30153984 0.70197519 0.20963911]]


In [37]:
b=np.random.rand(3)*10 #it generates random values 
print(b)

[8.87544806 1.57754431 0.84203136]


# Reshaping the array objects

<img src="reshape.png">

In [39]:
import numpy as np  
a = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(a)
a=a.reshape(2,3)  
print("printing the reshaped array..")  
print(a)  

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]


# SLICING IN NUMPY

In [40]:
import numpy as np 
a=np.arange(10)
print("THE ORIGINAL ARRAY:",a)
print("\n")
print(a[2:7:2])
print(a[2:5])
print(a[2:])

THE ORIGINAL ARRAY: [0 1 2 3 4 5 6 7 8 9]


[2 4 6]
[2 3 4]
[2 3 4 5 6 7 8 9]


In [41]:
import numpy as np 
a=np.arange(10)
print("THE ORIGINAL ARRAY:",a)
s=slice(2,7,2)
c=a[5]
print(c)
print(a[s])

THE ORIGINAL ARRAY: [0 1 2 3 4 5 6 7 8 9]
5
[2 4 6]


<img src="slicing ex.jpg">

Ellipsis can also be used along with basic slicing.
Ellipsis (…) is the number of : objects needed to make a selection tuple of
the same length as the dimensions of the array.

In [44]:
# Python program for indexing using 
# basic slicing with ellipsis
import numpy as np
 
# A 3 dimensional array.
b = np.array([[[1, 2, 3],[4, 5, 6]],
              [[7, 8, 9],[10, 11, 12]]])
 
print(b[...,1]) #Equivalent to b[: ,: ,1 ]

[[ 2  5]
 [ 8 11]]


In [45]:
import numpy as np
x=np.array([('rex',9,81.0),('fido',3,27.0)],dtype=[('name','U2'),('age','i4'),('weight','f4')])
a=x[0]
print(a)
print("\n")
print(x['name'])

('re', 9, 81.)


['re' 'fi']


In [48]:
import numpy as np  
a=np.linspace(5,15,10,dtype=int) #prints 10 values which are evenly spaced over the given interval 5-15  
print(a) 

[ 5  6  7  8  9 10 11 12 13 15]


# NumPy Array Axis

A NumPy multi-dimensional array is represented by the axis where axis-0 represents the columns and axis-1 represents the rows. We can mention the axis to perform row-level or column-level calculations like the addition of row or column elements.

<img src="axis.png">

In [51]:
import numpy as np  
a = np.array([[1,2,30],[10,15,4]])  
print("The array:",a)  
print("The maximum elements of columns:",a.max(axis=0))   
print("The minimum element of rows",a.min(axis=1))  
print("The sum of all rows",a.sum(axis=1))  

The array: [[ 1  2 30]
 [10 15  4]]
The maximum elements of columns: [10 15 30]
The minimum element of rows [1 4]
The sum of all rows [33 29]


In [54]:
import numpy as np  
a = np.array([[1,2,30],[10,15,4]])  
print(np.sqrt(a))  
print(np.std(a))

[[1.         1.41421356 5.47722558]
 [3.16227766 3.87298335 2.        ]]
10.044346115546242


In [56]:
#ADDITION, MULTIPLICATION , DIVISION
import numpy as np  
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Sum of array a and b\n",a+b)  
print("Product of array a and b\n",a*b)  
print("Division of array a and b\n",a/b)  

Sum of array a and b
 [[ 2  4 33]
 [22 34 33]]
Product of array a and b
 [[  1   4  90]
 [120 285 116]]
Division of array a and b
 [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


Array Concatenation
The numpy provides us with the vertical stacking and horizontal stacking which allows us to concatenate two multi-dimensional arrays vertically or horizontall

In [57]:
import numpy as np  
a = np.array([[1,2,30],[10,15,4]])  
b = np.array([[1,2,3],[12, 19, 29]])  
print("Arrays vertically concatenated\n",np.vstack((a,b)));  
print("Arrays horizontally concatenated\n",np.hstack((a,b)))  

Arrays vertically concatenated
 [[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
Arrays horizontally concatenated
 [[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]


# BOOLEAN_INDEXING

In [44]:
import numpy as np
a=np.array([1,2,3,9,10,11])
b=np.array([4,5,6,7,8,20])
print(a)
print(b)

[ 1  2  3  9 10 11]
[ 4  5  6  7  8 20]


In [45]:
#extract values greater than 10
bool_arr=b>10
print(bool_arr)

[False False False False False  True]


In [47]:
new_arr=b[bool_arr]   #if we to find which value is true
new_arr

array([20])

In [50]:
new_arr=b[(b>5) & (b<18)]
new_arr

array([6, 7, 8])

In [53]:
b[:3]=19
b

array([19, 19, 19,  7,  8, 20])

In [55]:
b[b>18]=100    #updating the values
b

array([100, 100, 100,   7,   8, 100])

In [59]:
#2d array 
import numpy as np
a=np.random.randint(1,30,(5,6))
print(a)

[[29  1 15 25  6 14]
 [23 25 27 16 22  2]
 [28  9 19  5 16  6]
 [ 9  9  9 23 29 23]
 [11 11 26  1 15  9]]


In [60]:
bool_arr=a>20
print(bool_arr)

[[ True False False  True False False]
 [ True  True  True False  True False]
 [ True False False False False False]
 [False False False  True  True  True]
 [False False  True False False False]]


In [61]:
ans=a[bool_arr]
print(ans)

[29 25 23 25 27 22 28 23 29 23 26]


# NumPy Broadcasting

In [65]:
import numpy as np  
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,14])  
c = a*b;  
print(c)  

[ 2  8 18 32 50 72 98]


In [66]:
#array of different SHAPE
import numpy as np  
a = np.array([1,2,3,4,5,6,7])  
b = np.array([2,4,6,8,10,12,14,19])  
c = a*b;  
print(c)  

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [67]:
import numpy as np  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
b = np.array([2,4,6,8])  
print("\nprinting array a..")  
print(a)  
print("\nprinting array b..")  
print(b)  
print("\nAdding arrays a and b ..")  
c = a + b;  
print(c)  


printing array a..
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]

printing array b..
[2 4 6 8]

Adding arrays a and b ..
[[ 3  6  9 12]
 [ 4  8 11 14]
 [12 24 45 11]]


<img src="add.png">

# NumPy Array Iteration

In [69]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("printing array")
print(a)
for x in np.nditer(a):
    print(x,end=" ")

printing array
[[1 2 3]
 [4 5 6]]
1 2 3 4 5 6 

In [67]:
import numpy as np  
a = np.array([[1,2,3,4],[2,4,5,6],[10,20,39,3]])  
print("Printing the array:")  
print(a)  
print("\n")
print("Printing the transpose of the array:")  
y=np.transpose(a)
print(y) 


Printing the array:
[[ 1  2  3  4]
 [ 2  4  5  6]
 [10 20 39  3]]


Printing the transpose of the array:
[[ 1  2 10]
 [ 2  4 20]
 [ 3  5 39]
 [ 4  6  3]]


In [74]:
#floor mathematical function
import numpy as np  
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.floor(arr))  

[ 12.  90. 123.  23.]


In [75]:
#ceil mathematical function 
import numpy as np  
arr = np.array([12.202, 90.23120, 123.020, 23.202])  
print(np.ceil(arr))  

[ 13.  91. 124.  24.]


# QUESTIONS PRACTISE  

In [78]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [83]:
import numpy as np
a=np.arange(9,50)
print(a)

[ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32
 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [84]:
import numpy as np
b=np.eye(5,6,dtype="int")
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


<img src="cn.png">
<img src="c.png">
<img src="d.png">
<img src="e.png">

In [87]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
a=input_[2, :3]
for i in a:
   print(i,end=" ")
print()
a=input_[1:4,3 ]
for j in a:
    print(j,end=" ")
print()
c=input_[2:5, 0:5]
for k in c:
    for l in k:
        print(l,end=" ")
print()
d=input_[1:3, 1:3]
for m in d:
    for n in m:
        print(n,end=" ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 